name: patisserie_app
description: Gestion de stock - Pâtisserie Orientale
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  google_sign_in: ^6.1.6
  googleapis: ^12.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  animate_do: ^3.3.4
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0
  provider: ^6.1.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
